apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proyecto
  template:
    metadata:
      labels:
        app: proyecto
    spec:
      containers:
      - name: proyecto
        image: ferderueda7/proyecto
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---

kind: Service
apiVersion: v1
metadata:
  name: proyecto-svc
spec:
  selector:
    app: proyecto
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
